
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A CONECTAR FUENTE ID NUMERO OPERADOR REPLICAS SIMULAR SUMIDERO TIEMPO_SERVICIOprograma : lista_instruccioneslista_instrucciones : lista_instrucciones instruccionlista_instrucciones : instruccioninstruccion : declaracion_fuente\n| declaracion_operador\n| declaracion_sumidero\n| declaracion_conectar\n| declaracion_simulardeclaracion_fuente : FUENTE IDdeclaracion_operador : OPERADOR ID TIEMPO_SERVICIO NUMEROdeclaracion_operador : OPERADOR ID TIEMPO_SERVICIO NUMERO REPLICAS NUMEROdeclaracion_sumidero : SUMIDERO IDdeclaracion_conectar : CONECTAR ID A IDdeclaracion_simular : SIMULAR NUMERO'
    
_lr_action_items = {'FUENTE':([0,2,3,4,5,6,7,8,14,15,17,19,22,23,25,],[9,9,-3,-4,-5,-6,-7,-8,-2,-9,-12,-14,-10,-13,-11,]),'OPERADOR':([0,2,3,4,5,6,7,8,14,15,17,19,22,23,25,],[10,10,-3,-4,-5,-6,-7,-8,-2,-9,-12,-14,-10,-13,-11,]),'SUMIDERO':([0,2,3,4,5,6,7,8,14,15,17,19,22,23,25,],[11,11,-3,-4,-5,-6,-7,-8,-2,-9,-12,-14,-10,-13,-11,]),'CONECTAR':([0,2,3,4,5,6,7,8,14,15,17,19,22,23,25,],[12,12,-3,-4,-5,-6,-7,-8,-2,-9,-12,-14,-10,-13,-11,]),'SIMULAR':([0,2,3,4,5,6,7,8,14,15,17,19,22,23,25,],[13,13,-3,-4,-5,-6,-7,-8,-2,-9,-12,-14,-10,-13,-11,]),'$end':([1,2,3,4,5,6,7,8,14,15,17,19,22,23,25,],[0,-1,-3,-4,-5,-6,-7,-8,-2,-9,-12,-14,-10,-13,-11,]),'ID':([9,10,11,12,21,],[15,16,17,18,23,]),'NUMERO':([13,20,24,],[19,22,25,]),'TIEMPO_SERVICIO':([16,],[20,]),'A':([18,],[21,]),'REPLICAS':([22,],[24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'lista_instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,14,]),'declaracion_fuente':([0,2,],[4,4,]),'declaracion_operador':([0,2,],[5,5,]),'declaracion_sumidero':([0,2,],[6,6,]),'declaracion_conectar':([0,2,],[7,7,]),'declaracion_simular':([0,2,],[8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> lista_instrucciones','programa',1,'p_programa','parser.py',130),
  ('lista_instrucciones -> lista_instrucciones instruccion','lista_instrucciones',2,'p_lista_instrucciones_multiple','parser.py',135),
  ('lista_instrucciones -> instruccion','lista_instrucciones',1,'p_lista_instrucciones_simple','parser.py',140),
  ('instruccion -> declaracion_fuente','instruccion',1,'p_instruccion','parser.py',145),
  ('instruccion -> declaracion_operador','instruccion',1,'p_instruccion','parser.py',146),
  ('instruccion -> declaracion_sumidero','instruccion',1,'p_instruccion','parser.py',147),
  ('instruccion -> declaracion_conectar','instruccion',1,'p_instruccion','parser.py',148),
  ('instruccion -> declaracion_simular','instruccion',1,'p_instruccion','parser.py',149),
  ('declaracion_fuente -> FUENTE ID','declaracion_fuente',2,'p_declaracion_fuente','parser.py',154),
  ('declaracion_operador -> OPERADOR ID TIEMPO_SERVICIO NUMERO','declaracion_operador',4,'p_declaracion_operador_simple','parser.py',159),
  ('declaracion_operador -> OPERADOR ID TIEMPO_SERVICIO NUMERO REPLICAS NUMERO','declaracion_operador',6,'p_declaracion_operador_replicado','parser.py',168),
  ('declaracion_sumidero -> SUMIDERO ID','declaracion_sumidero',2,'p_declaracion_sumidero','parser.py',174),
  ('declaracion_conectar -> CONECTAR ID A ID','declaracion_conectar',4,'p_declaracion_conectar','parser.py',179),
  ('declaracion_simular -> SIMULAR NUMERO','declaracion_simular',2,'p_declaracion_simular','parser.py',184),
]
